import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface InvoiceData {
  invoice_number: string;
  client_name: string;
  client_email: string;
  client_address: string | null;
  issue_date: string;
  due_date: string;
  notes: string | null;
  total: number;
  freelancer_name: string;
  freelancer_company: string;
  invoice_line_items: Array<{
    description: string;
    quantity: number;
    unit_price: number;
  }>;
}

export async function generateInvoicePDF(invoice: InvoiceData): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage();
  const { width } = page.getSize();
  const margin = 50;
  let y = page.getHeight() - margin;

  const drawText = (text: string, x: number, yPos: number, font: typeof helvetica, size: number, color = rgb(0, 0, 0)) => {
    page.drawText(text, { x, y: yPos, font, size, color });
  };

  drawText("INVOICE", margin, y, helveticaBold, 24, rgb(0.15, 0.39, 0.92));
  y -= 25;
  drawText(invoice.invoice_number, margin, y, helvetica, 11);
  y -= 15;

  // From section (right side)
  const fromX = width - 200;
  drawText("FROM", fromX, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  y -= 12;
  drawText(invoice.freelancer_name, fromX, y, helvetica, 11);
  if (invoice.freelancer_company) {
    y -= 12;
    drawText(invoice.freelancer_company, fromX, y, helvetica, 11);
  }
  y -= 30;

  // Bill To
  drawText("BILL TO", margin, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  y -= 12;
  drawText(invoice.client_name, margin, y, helvetica, 11);
  y -= 12;
  drawText(invoice.client_email, margin, y, helvetica, 11);
  if (invoice.client_address) {
    y -= 12;
    drawText(invoice.client_address, margin, y, helvetica, 11);
  }

  // Dates
  const datesX = width - 200;
  drawText("Issue Date:", datesX, y + 36, helvetica, 9, rgb(0.42, 0.45, 0.5));
  drawText(invoice.issue_date, datesX + 70, y + 36, helvetica, 11);
  drawText("Due Date:", datesX, y + 24, helvetica, 9, rgb(0.42, 0.45, 0.5));
  drawText(invoice.due_date, datesX + 70, y + 24, helvetica, 11);
  y -= 40;

  // Table header
  drawText("Description", margin, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  drawText("Qty", margin + 250, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  drawText("Unit Price", margin + 300, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  drawText("Total", margin + 380, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
  y -= 15;

  // Line items
  for (const item of invoice.invoice_line_items) {
    drawText(item.description.substring(0, 35), margin, y, helvetica, 10);
    drawText(item.quantity.toString(), margin + 250, y, helvetica, 10);
    drawText(`$${item.unit_price.toFixed(2)}`, margin + 300, y, helvetica, 10);
    drawText(`$${(item.quantity * item.unit_price).toFixed(2)}`, margin + 380, y, helvetica, 10);
    y -= 15;
  }

  // Total
  y -= 10;
  drawText("Total:", margin + 320, y, helveticaBold, 12);
  drawText(`$${invoice.total.toFixed(2)}`, margin + 380, y, helveticaBold, 12, rgb(0.15, 0.39, 0.92));

  // Notes
  if (invoice.notes) {
    y -= 30;
    drawText("NOTES", margin, y, helveticaBold, 9, rgb(0.42, 0.45, 0.5));
    y -= 12;
    drawText(invoice.notes, margin, y, helvetica, 10);
  }

  // Footer
  y -= 40;
  drawText("Generated by InvoiceFlow", width / 2 - 60, y, helvetica, 9, rgb(0.42, 0.45, 0.5));

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
